spring:
  application:
    name: producer-service

server:
  port: 8081


eureka:
  uri: http://localhost:8761
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${eureka.uri:http://127.0.0.1:8761}/eureka/

info:
  app:
    name: ${spring.application.name}
    description: Configuration service
    version: @project.version@
    artifact: @project.artifactId@